### ISSUE TITLE
Commits over on the Feather branch that need to be incorporated here

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/FeatherLib.jl#4]
This is just tracking them:
- [x] https://github.com/JuliaData/Feather.jl/pull/78/commits/472522fcab7a3e9cf52cf1789350205a4857f885
- [x] https://github.com/JuliaData/Feather.jl/pull/78/commits/748f2860a0117ef0f44035fd3fcb8eddf5ec65a8
- [x] https://github.com/JuliaData/Feather.jl/commit/b5bc7c53204e63cc0ab3c7a94e7746d8cec7be23
- [x] https://github.com/JuliaData/Feather.jl/commit/5f317cd8ee13ffa815f5e7062f25f4114ed10a7e
- [x] https://github.com/JuliaData/Feather.jl/commit/1fb65b76a8b16ffdb18279fafa64b6d4470e111f

**Comment by ExpandingMan** [comment]
I'm going to make a couple of PR's to this soon that should incorporate these.

**Comment by davidanthoff** [comment]
I'm starting to work on catching up with your work over on the Feather.jl PR. If you've started on that already, shout now to stop me :)

**Comment by ExpandingMan** [comment]
Yeah, sorry David, I'm afraid if your only issue is with breaking compatibility with DataFrames v0.10 then you are going to be on your own.  I just don't see any of the rest of us worrying about that and I'm sure that once 0.7 is out we'll all be chomping at the bit to leave everything pre 0.7 in the dust.

I'm sorry to hear that you are in a position where dropping it is not an option for you.  That's quite different from my experience of how things work in an academic setting when I was a graduate student, so that reason is not at all what I was expecting initially: I could certainly imagine you having students coming up on a publication or their thesis needing things to just not break, but in those scenarios I wouldn't think they'd be making much use of new code anyway.  Perhaps Pkg3 will alleviate *some* of your problems as the old Pkg can certainly be quite infuriating even under normal circumstances.

Anyway best of luck; I'm sure we'll all continue to collaborate as much as possible wherever legacy compatibility is not quite so big an issue :smile:

I think what you see in the PR right now should be *pretty* close to whatever the final form will look like, so it may be worth doing this now.
